name: Android Testing CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: ./.github/actions/setup-java

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # - name: Unit Test
      #   uses: ./.github/actions/setup-test

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}